name: gnome-42-2204
version: git
summary: Shared GNOME 42 Ubuntu stack
description: |
  This snap provides the GNOME 42 stack to other snaps that use it. It shares the base GNOME libraries and desktop integration components through the content interface. This helps reduce the size of snaps and helps developers to easily snap desktop applications.

  **For users**

  This snap is automatically installed and removed when needed. **Manually adding or removing this snap is not recommended** and might break things.

  * If you are having issues with **snaps** using GNOME, please contact the experts on the Snapcraft forum: https://forum.snapcraft.io/
  * If you want to install the GNOME Desktop Environment, then you are in the wrong place. Please take a look at https://www.gnome.org/ for more information on how to get it.

  **For developers**

  * The `gnome` extension is the recommended way to use this in your own snap: https://snapcraft.io/docs/gnome-extension
  * You can report issues with this content snap on GitHub: https://github.com/ubuntu/gnome-sdk/issues
  * The source code of this snap is available on GitHub in the `gnome-42-2204` branch: https://github.com/ubuntu/gnome-sdk/tree/gnome-42-2204
contact: https://github.com/ubuntu/gnome-sdk/issues

confinement: strict
grade: stable
icon: icon.png
base: core22
compression: lzo

package-repositories:
  - type: apt
    ppa: ubuntu-asahi/ubuntu-asahi-next

architectures:
  - arm64

# the recommended mountpoint for that content is /gnome-platform
slots:
    gnome-42-2204:
      interface: content
      read:
        - /

parts:
  gnome:
    plugin: nil
    stage-snaps: [ gnome-42-2204/latest/stable ]
    stage:
      # libegl-mesa0
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libEGL_mesa.so.0.0.0
      - -usr/share/glvnd/egl_vendor.d
      # libgbm1
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libgbm.so.1.0.0
      # libglapi-mesa
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libglapi.so.0.0.0
      # libglu1-mesa
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libGLU.so.1.3.1
      # libglx-mesa0
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libGLX_mesa.so.0.0.0
      # libgl1-mesa-dri
      # mesa-va-drivers
      - -usr/lib/$CRAFT_ARCH_TRIPLET/dri
      - -usr/share/drirc.d
      # mesa-vulkan-drivers
      - -usr/bin/mesa-overlay-control.py
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libVkLayer*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libvulkan*
      - -usr/share/vulkan/explicit_layer.d
      - -usr/share/vulkan/icd.d
      - -usr/share/vulkan/implicit_layer.d
      # libdrm2
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libdrm.so.2.4.0
      # libdrm-common
      - -usr/share/libdrm
      # libdrm-*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libdrm_amdgpu.so.1.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libdrm_nouveau.so.2.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libdrm_radeon.so.1.0.1
      # libvdpau1
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libvdpau.so.1.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET/vdpau/libvdpau_trace.so.1.0.0

  debs:
    after: [ gnome ]
    plugin: nil
    stage-packages:
      # mesa
      - libegl-mesa0
      - libgbm1
      - libgl1-mesa-dri
      - libglapi-mesa
      - libglu1-mesa
      - libglx-mesa0
      - mesa-va-drivers
      - mesa-vulkan-drivers
      # libdrm
      - libdrm2
      - libdrm-common
      - libdrm-amdgpu1
      - libdrm-nouveau2
      - libdrm-radeon1
      # libvdpau
      - libvdpau1
    stage:
      # libegl-mesa0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libEGL_mesa.so.0.0.0
      - usr/share/glvnd/egl_vendor.d
      # libgbm1
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgbm.so.1.0.0
      # libglapi-mesa
      - usr/lib/$CRAFT_ARCH_TRIPLET/libglapi.so.0.0.0
      # libglu1-mesa
      - usr/lib/$CRAFT_ARCH_TRIPLET/libGLU.so.1.3.1
      # libglx-mesa0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libGLX_mesa.so.0.0.0
      # libgl1-mesa-dri
      # mesa-va-drivers
      - usr/lib/$CRAFT_ARCH_TRIPLET/dri
      - usr/share/drirc.d
      # mesa-vulkan-drivers
      - usr/bin/mesa-overlay-control.py
      - usr/lib/$CRAFT_ARCH_TRIPLET/libVkLayer*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libvulkan*
      - usr/share/vulkan/explicit_layer.d
      - usr/share/vulkan/icd.d
      - usr/share/vulkan/implicit_layer.d
      # libdrm-common
      - usr/share/libdrm
      # libdrm2
      - usr/lib/$CRAFT_ARCH_TRIPLET/libdrm.so.2.4.0
      # libdrm-*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libdrm_amdgpu.so.1.0.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libdrm_nouveau.so.2.0.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libdrm_radeon.so.1.0.1
      # libvdpau1
      - usr/lib/$CRAFT_ARCH_TRIPLET/libvdpau.so.1.0.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/vdpau/libvdpau_trace.so.1.0.0
